### PR TITLE
Add convert to Halogen

### PR DESCRIPTION
**Pull request by deemp**
First of all thank you, @dnikolovv!
Now, about PR. This version seems to work for simple cases. Also, I suggest adding tabs for switching between React and Halogen code.

Sample HTML:
```html
<section class="a-class b-class">
  <h1>Some heading</h1>
  <p>A paragraph.</p>
</section>

<section class="a-class">
  <h1>Some heading</h1>
  <p>A paragraph.</p>
</section>
```

Purescript output:
```purs
import Halogen.HTML as HH
import Halogen as H
import Halogen.HTML.Properties as HP
import Web.HTML.Common as WC
import Halogen.Query.Event as HQE

node0 = HH.section [ classes_ [ "a-class", "b-class" ] ]
  [ HH.h1_ [ HH.text "Some heading" ], HH.p_ [ HH.text "A paragraph." ] ]

node1 = HH.section [ classes_ [ "a-class" ] ]
  [ HH.h1_ [ HH.text "Some heading" ], HH.p_ [ HH.text "A paragraph." ] ]

class_ ∷ ∀ (a ∷ Row Type) (b ∷ Type). String → HH.IProp (class ∷ String | a) b
class_ n = HP.class_ $ WC.ClassName n

attr_ ∷ ∀ (a ∷ Row Type) (b ∷ Type). String → String → HH.IProp a b
attr_ k v = HP.attr (H.AttrName k) v

classes_ ∷ ∀ (a ∷ Row Type) (b ∷ Type). Array String → HH.IProp (class ∷ String | a) b
classes_ n = HP.classes $ WC.ClassName <$> n

```

### CODE REVIEW

**Comment by dnikolovv** [comment]
Hey @br4ch1st0chr0n3! Thank you for contributing!

Looks great! The thing I'm concerned about is the unicode. What do you think about switching to ascii like: `::` instead of `∷`, `forall` instead of `∀`, and so on.

At least in my experience, it's very rare to see projects that use unicode, so it might be best to support the more common usage (or ideally have the user choose what they want).

**Comment by deemp** [comment]
Sure, @dnikolovv. Fixed it

**Comment by deemp** [comment]
Now
```html
<section class="a-class" b>
  <h1>Some heading</h1>
  <p>A paragraph.</p>
</section>
```
becomes
```purs
import Halogen as H
import Halogen.HTML as HH
import Halogen.HTML.Properties as HP

-- HTML starts here

node0 :: forall (a :: Type) (b :: Type). HTML a b
node0 = HH.section [ classes_ [ "a-class" ], attr_ "b" "" ]
  [ HH.h1_ [ HH.text "Some heading" ], HH.p_ [ HH.text "A paragraph." ] ]

-- End of HTML

attr_ :: forall (a :: Row Type) (b :: Type). String -> String -> HP.IProp a b
attr_ k v = HP.attr (H.AttrName k) v

classes_
  :: forall (a :: Row Type) (b :: Type)
   . Array String
  -> HP.IProp (class :: String | a) b
classes_ n = HP.classes $ H.ClassName <$> n

```

**Comment by dnikolovv** [comment]
Great, thanks! I'll be merging this and maybe we can do the tabs soon.

**Comment by deemp** [comment]
Nice!

**Pull request merged**
